export default {
  cross: require('./cross.png'),
  back: require('./back.png'),
  refresh: require('./refresh.png'),
  logo_main: require('./logo_main.jpg'),
  bg_header: require('./bg_header.jpg'),
  es_logo_white: require('./es_logo_white.png'),
  es_bg: require('./es_bg.gif'),
  email: require('./email.png'),
  mobile: require('./mobile.png'),
  upload: require('./upload.png'),
  checkbox_checked: require('./checkbox_checked.png'),
  checkbox_unchecked: require('./checkbox_unchecked.png'),
  agent_contact_image: require('./agent.png'),
  arrow_down: require('./arrow-down.png'),
  arrow_up: require('./arrow-up.png'),
  arrow_exchange: require('./arrow-exchange.png'),
  ar: require('./AR.png'),
  factsheet: require('./factsheet.png'),
  product: require('./product.png'),
  prospectus: require('./prospectus.png'),
  sp: require('./SP.png'),
  logo_eib: require('./logo_eib.png'),
  whiteLogo: require('./whiteLogo.png'),
  idea: require('./idea.png'),
};
